version: '3.8'

services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    hostname: redis
    container_name: redis_db
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"

volumes:
  redis-data:
  postgres_data:
